FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit==1.35.0 \
    plotly==5.22.0 \
    pandas==2.2.2 \
    requests==2.32.3 \
    psycopg2-binary==2.9.9 \
    sqlalchemy==2.0.30 \
    joblib==1.4.2 \
    scikit-learn==1.5.0

COPY src/dashboard /app

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
