FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi==0.111.0 \
    uvicorn==0.30.0 \
    psycopg2-binary==2.9.9 \
    sqlalchemy==2.0.30 \
    pandas==2.2.2 \
    joblib==1.4.2 \
    scikit-learn==1.5.0

COPY src/api /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
